### ISSUE TITLE
autopush (master) job failing to run, on qa-preprod

### ISSUE THREAD

**Issue by stephendonner** [mozilla-services/autopush-integration-tests#119]
@rpappalax are you still able to help with this? (or @karlht know whom might be?)

none of the autopush jobs on qa-preprod are passing; master fails with:

```
[Pipeline] { (Test)
[Pipeline] sh
06:15:24 [autopush_master-LY4IHD6FM7NR5WWOESTTUB2LW5QKTV2WTWASHQZN74WA2ZKDUMHQ] Running shell script
06:15:24 + /home/jenkins/workspace/autopush_master-LY4IHD6FM7NR5WWOESTTUB2LW5QKTV2WTWASHQZN74WA2ZKDUMHQ/run
06:15:24 /home/jenkins/workspace/autopush_master-LY4IHD6FM7NR5WWOESTTUB2LW5QKTV2WTWASHQZN74WA2ZKDUMHQ@tmp/durable-80498f79/script.sh: line 2: /home/jenkins/workspace/autopush_master-LY4IHD6FM7NR5WWOESTTUB2LW5QKTV2WTWASHQZN74WA2ZKDUMHQ/run: No such file or directory
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] mail
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected

ERROR: script returned exit code 1
Finished: FAILURE
```

https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/autopush/job/master/

**Comment by karlht** [comment]
I think Richard's the right person, here.  Failing that, I would try, in order: Chris, Dave, and ckolos/oremj.

**Comment by rpappalax** [comment]
@stephendonner howdy Stephen, afaik this job isn't yet ready to run.  I was working on standing up a job as we got automation rolled out, but it's not there yet (hence the reason it's only on preprod).  I'd set this one aside for now if you don't mind however, If you need me to jump back in on this immediately, please ping me on Monday and I will try to set aside some time from my sprint to look into it.

**Comment by stephendonner** [comment]
Thanks, @rpappalax - not pushing this as a priority for you; just happened to notice it, esp. since the move to the /mozilla/ GitHub org.
